import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "animate.css/animate.css";
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HiringKit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ width: "100vw", overflowX: "hidden" }}>
      <head>
        <link rel="icon" href="/Logo.PNG" />
      </head>
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col max-w-[100vw] overflow-x-hidden">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
